name: xpfitness
description: "Fitness App"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.3.2
  health: ^11.1.0
  provider: ^6.0.0
  app_settings: ^4.1.0
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_ui_auth: ^1.16.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.4.0
  cloud_firestore: ^5.4.4
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.7.0
  gauge_indicator: ^0.4.3
  fitbitter: ^2.0.4
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
