import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:healthcore/constants/colors.constants.dart';
import 'package:healthcore/enums/health_item_type.enum.dart';
import 'package:healthcore/models/monthly_medal.model.dart';

enum MedalType {
  monthlyAverage,  // Based on average for a specific month
  monthlyTotal,    // Based on total for a specific month
}

class MedalDefinitions {
  static List<Medal> getMonthlyAverageMedals(String monthKey, Map<HealthItemType, double> monthlyAverages) {
    return [
      // STEPS MONTHLY AVERAGE
      _createMonthlyMedal(
        baseId: 'steps-avg_15k',
        monthKey: monthKey,
        title: 'Elite Stepper',
        description: 'Averaged 15,000 steps daily - surpassing WHO\'s recommended goal by 50%!',
        icon: FontAwesomeIcons.personRunning,
        color: CoreColors.coreDiamond,
        type: HealthItemType.steps,
        requirement: 15000,
        tier: 4,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.steps] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'steps-avg_10k',
        monthKey: monthKey,
        title: 'Step Master',
        description: 'Averaged 10,000 steps daily - meeting the perfect healthy lifestyle goal!',
        icon: FontAwesomeIcons.personWalking,
        color: CoreColors.coreGold,
        type: HealthItemType.steps,
        requirement: 10000,
        tier: 3,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.steps] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'steps-avg_7500',
        monthKey: monthKey,
        title: 'Active Achiever',
        description: 'Averaged 7,500 steps daily - you\'re in the top 30% of active people!',
        icon: FontAwesomeIcons.personWalking,
        color: CoreColors.coreSilver,
        type: HealthItemType.steps,
        requirement: 7500,
        tier: 2,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.steps] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'steps-avg_5000',
        monthKey: monthKey,
        title: 'Consistent Stepper',
        description: 'Averaged 5,000 steps daily - building healthy habits one step at a time!',
        icon: FontAwesomeIcons.shoePrints,
        color: CoreColors.coreBronze,
        type: HealthItemType.steps,
        requirement: 5000,
        tier: 1,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.steps] ?? 0,
      ),

      // STRENGTH TRAINING TIME MONTHLY AVERAGE
      _createMonthlyMedal(
        baseId: 'strength-avg_60',
        monthKey: monthKey,
        title: 'Iron Master',
        description: 'Averaged 60 minutes of daily strength training - enough to build muscle like a Greek statue!',
        icon: FontAwesomeIcons.dumbbell,
        color: CoreColors.coreDiamond,
        type: HealthItemType.strengthTrainingTime,
        requirement: 60,
        tier: 4,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.strengthTrainingTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'strength-avg_45',
        monthKey: monthKey,
        title: 'Strength Champion',
        description: 'Averaged 45 minutes of daily strength training - the perfect balance for muscle growth and recovery!',
        icon: FontAwesomeIcons.weightHanging,
        color: CoreColors.coreGold,
        type: HealthItemType.strengthTrainingTime,
        requirement: 45,
        tier: 3,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.strengthTrainingTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'strength-avg_30',
        monthKey: monthKey,
        title: 'Resistance Ruler',
        description: 'Averaged 30 minutes of daily strength training - enough to trigger optimal protein synthesis!',
        icon: FontAwesomeIcons.personWalking,
        color: CoreColors.coreSilver,
        type: HealthItemType.strengthTrainingTime,
        requirement: 30,
        tier: 2,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.strengthTrainingTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'strength-avg_15',
        monthKey: monthKey,
        title: 'Strength Builder',
        description: 'Averaged 15 minutes of daily strength training - even short sessions can increase bone density by 1-3%!',
        icon: FontAwesomeIcons.handFist,
        color: CoreColors.coreBronze,
        type: HealthItemType.strengthTrainingTime,
        requirement: 15,
        tier: 1,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.strengthTrainingTime] ?? 0,
      ),

      // CARDIO TIME MONTHLY AVERAGE
      _createMonthlyMedal(
        baseId: 'cardio-avg_60',
        monthKey: monthKey,
        title: 'Cardio King',
        description: 'Averaged 60 minutes of daily cardio - enough to burn about 700-1000 calories daily!',
        icon: FontAwesomeIcons.heartPulse,
        color: CoreColors.coreDiamond,
        type: HealthItemType.cardioTime,
        requirement: 60,
        tier: 4,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.cardioTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'cardio-avg_45',
        monthKey: monthKey,
        title: 'Endurance Expert',
        description: 'Averaged 45 minutes of daily cardio - reducing your resting heart rate by up to 10 beats per minute!',
        icon: FontAwesomeIcons.personRunning,
        color: CoreColors.coreGold,
        type: HealthItemType.cardioTime,
        requirement: 45,
        tier: 3,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.cardioTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'cardio-avg_30',
        monthKey: monthKey,
        title: 'Aerobic Achiever',
        description: 'Averaged 30 minutes of daily cardio - meeting the American Heart Association\'s recommendation!',
        icon: FontAwesomeIcons.personBiking,
        color: CoreColors.coreSilver,
        type: HealthItemType.cardioTime,
        requirement: 30,
        tier: 2,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.cardioTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'cardio-avg_15',
        monthKey: monthKey,
        title: 'Cardio Starter',
        description: 'Averaged 15 minutes of daily cardio - even short bursts can increase your lifespan by 3 years!',
        icon: FontAwesomeIcons.shoePrints,
        color: CoreColors.coreBronze,
        type: HealthItemType.cardioTime,
        requirement: 15,
        tier: 1,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.cardioTime] ?? 0,
      ),

      // SLEEP MONTHLY AVERAGE
      _createMonthlyMedal(
        baseId: 'sleep-avg_9h',
        monthKey: monthKey,
        title: 'Sleep Champion',
        description: 'Averaged 9 hours of sleep daily - optimal rest for peak performance!',
        icon: FontAwesomeIcons.moon,
        color: CoreColors.coreDiamond,
        type: HealthItemType.sleep,
        requirement: 540, // minutes
        tier: 4,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep-avg_8h',
        monthKey: monthKey,
        title: 'Rest Master',
        description: 'Averaged 8 hours of sleep daily - the perfect night\'s rest!',
        icon: FontAwesomeIcons.bed,
        color: CoreColors.coreGold,
        type: HealthItemType.sleep,
        requirement: 480,
        tier: 3,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep-avg_7h',
        monthKey: monthKey,
        title: 'Sleep Tracker',
        description: 'Averaged 7 hours of sleep daily - maintaining healthy sleep habits!',
        icon: FontAwesomeIcons.cloudMoon,
        color: CoreColors.coreSilver,
        type: HealthItemType.sleep,
        requirement: 420,
        tier: 2,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep-avg_6h',
        monthKey: monthKey,
        title: 'Rest Achiever',
        description: 'Averaged 6 hours of sleep daily - working on better sleep habits!',
        icon: FontAwesomeIcons.clock,
        color: CoreColors.coreBronze,
        type: HealthItemType.sleep,
        requirement: 360,
        tier: 1,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.sleep] ?? 0,
      ),

      // PROTEIN MONTHLY AVERAGE
      _createMonthlyMedal(
        baseId: 'protein-avg_150',
        monthKey: monthKey,
        title: 'Protein Elite',
        description: 'Averaged 150g protein daily - optimal for muscle growth!',
        icon: FontAwesomeIcons.drumstickBite,
        color: CoreColors.coreDiamond,
        type: HealthItemType.proteinIntake,
        requirement: 150,
        tier: 4,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein-avg_100',
        monthKey: monthKey,
        title: 'Protein Pro',
        description: 'Averaged 100g protein daily - perfect for active lifestyle!',
        icon: FontAwesomeIcons.egg,
        color: CoreColors.coreGold,
        type: HealthItemType.proteinIntake,
        requirement: 100,
        tier: 3,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein-avg_75',
        monthKey: monthKey,
        title: 'Protein Tracker',
        description: 'Averaged 75g protein daily - meeting basic fitness needs!',
        icon: FontAwesomeIcons.burger,
        color: CoreColors.coreSilver,
        type: HealthItemType.proteinIntake,
        requirement: 75,
        tier: 2,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein-avg_50',
        monthKey: monthKey,
        title: 'Protein Starter',
        description: 'Averaged 50g protein daily - building healthy eating habits!',
        icon: FontAwesomeIcons.blender,
        color: CoreColors.coreBronze,
        type: HealthItemType.proteinIntake,
        requirement: 50,
        tier: 1,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.proteinIntake] ?? 0,
      ),

      // NET CALORIES MONTHLY AVERAGE
      _createMonthlyMedal(
        baseId: 'netcalories-avg_800',
        monthKey: monthKey,
        title: 'Elite Deficit Creator',
        description: 'Averaged a perfect 800 calorie daily deficit - the optimal amount for sustainable fat loss!',
        icon: FontAwesomeIcons.weightScale,
        color: CoreColors.coreDiamond,
        type: HealthItemType.netCalories,
        requirement: -800,
        tier: 4,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.netCalories] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'netcalories-avg_600',
        monthKey: monthKey,
        title: 'Master Deficit Achiever',
        description: 'Averaged a 600 calorie daily deficit - enough to lose about 1.2 pounds per week!',
        icon: FontAwesomeIcons.chartLine,
        color: CoreColors.coreGold,
        type: HealthItemType.netCalories,
        requirement: -600,
        tier: 3,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.netCalories] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'netcalories-avg_400',
        monthKey: monthKey,
        title: 'Consistent Calorie Cutter',
        description: 'Averaged a 400 calorie daily deficit - a sustainable approach that preserves muscle mass!',
        icon: FontAwesomeIcons.fire,
        color: CoreColors.coreSilver,
        type: HealthItemType.netCalories,
        requirement: -400,
        tier: 2,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.netCalories] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'netcalories-avg_200',
        monthKey: monthKey,
        title: 'Deficit Starter',
        description: 'Averaged a 200 calorie daily deficit - small changes lead to long-term results!',
        icon: FontAwesomeIcons.bowlFood,
        color: CoreColors.coreBronze,
        type: HealthItemType.netCalories,
        requirement: -200,
        tier: 1,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.netCalories] ?? 0,
      ),
    ];
  }

  static List<Medal> getMonthlyTotalMedals(String monthKey, Map<HealthItemType, double> monthlyTotals) {
    return [
      // STEPS MONTHLY TOTALS
      _createMonthlyMedal(
        baseId: 'steps-total_400k',
        monthKey: monthKey,
        title: 'Monthly Marathon Master',
        description: 'Crushed 400,000 steps in a month - you\'ve walked the length of Ireland!',
        icon: FontAwesomeIcons.mountain,
        color: CoreColors.coreDiamond,
        type: HealthItemType.steps,
        requirement: 400000,
        tier: 4,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.steps] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'steps-total_300k',
        monthKey: monthKey,
        title: 'Monthly Explorer',
        description: 'Reached 300,000 steps in a month - equivalent to hiking the Grand Canyon rim-to-rim!',
        icon: FontAwesomeIcons.personHiking,
        color: CoreColors.coreGold,
        type: HealthItemType.steps,
        requirement: 300000,
        tier: 3,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.steps] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'steps-total_200k',
        monthKey: monthKey,
        title: 'Monthly Pathfinder',
        description: 'Completed 200,000 steps in a month - you\'ve walked the length of Manhattan 4 times!',
        icon: FontAwesomeIcons.route,
        color: CoreColors.coreSilver,
        type: HealthItemType.steps,
        requirement: 200000,
        tier: 2,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.steps] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'steps-total_100k',
        monthKey: monthKey,
        title: 'Monthly Stepper',
        description: 'Achieved 100,000 steps in a month - that\'s like walking the Golden Gate Bridge 30 times!',
        icon: FontAwesomeIcons.shoePrints,
        color: CoreColors.coreBronze,
        type: HealthItemType.steps,
        requirement: 100000,
        tier: 1,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.steps] ?? 0,
      ),

      // STRENGTH TRAINING TIME MONTHLY TOTALS
      _createMonthlyMedal(
        baseId: 'strength-total_1500',
        monthKey: monthKey,
        title: 'Monthly Muscle Maestro',
        description: 'Logged 1,500 minutes (25 hours) of strength training - enough to do 9,000 push-ups!',
        icon: FontAwesomeIcons.dumbbell,
        color: CoreColors.coreDiamond,
        type: HealthItemType.strengthTrainingTime,
        requirement: 1500,
        tier: 4,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.strengthTrainingTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'strength-total_1000',
        monthKey: monthKey,
        title: 'Monthly Iron Legend',
        description: 'Completed 1,000 minutes (16.7 hours) of strength training - equivalent to lifting the Eiffel Tower twice!',
        icon: FontAwesomeIcons.weightHanging,
        color: CoreColors.coreGold,
        type: HealthItemType.strengthTrainingTime,
        requirement: 1000,
        tier: 3,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.strengthTrainingTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'strength-total_750',
        monthKey: monthKey,
        title: 'Monthly Resistance Ruler',
        description: 'Achieved 750 minutes (12.5 hours) of strength training - like doing 4,500 squats!',
        icon: FontAwesomeIcons.personWalking,
        color: CoreColors.coreSilver,
        type: HealthItemType.strengthTrainingTime,
        requirement: 750,
        tier: 2,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.strengthTrainingTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'strength-total_500',
        monthKey: monthKey,
        title: 'Monthly Strength Builder',
        description: 'Completed 500 minutes (8.3 hours) of strength training - equivalent to moving 15 tons of weight!',
        icon: FontAwesomeIcons.handFist,
        color: CoreColors.coreBronze,
        type: HealthItemType.strengthTrainingTime,
        requirement: 500,
        tier: 1,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.strengthTrainingTime] ?? 0,
      ),

      // CARDIO TIME MONTHLY TOTALS
      _createMonthlyMedal(
        baseId: 'cardio-total_1500',
        monthKey: monthKey,
        title: 'Monthly Cardio Conqueror',
        description: 'Logged 1,500 minutes (25 hours) of cardio - equivalent to running from New York to Boston!',
        icon: FontAwesomeIcons.heartPulse,
        color: CoreColors.coreDiamond,
        type: HealthItemType.cardioTime,
        requirement: 1500,
        tier: 4,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.cardioTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'cardio-total_1000',
        monthKey: monthKey,
        title: 'Monthly Endurance Elite',
        description: 'Completed 1,000 minutes (16.7 hours) of cardio - like swimming across the English Channel!',
        icon: FontAwesomeIcons.personRunning,
        color: CoreColors.coreGold,
        type: HealthItemType.cardioTime,
        requirement: 1000,
        tier: 3,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.cardioTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'cardio-total_750',
        monthKey: monthKey,
        title: 'Monthly Aerobic Ace',
        description: 'Achieved 750 minutes (12.5 hours) of cardio - burning approximately 10,000 calories!',
        icon: FontAwesomeIcons.personBiking,
        color: CoreColors.coreSilver,
        type: HealthItemType.cardioTime,
        requirement: 750,
        tier: 2,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.cardioTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'cardio-total_500',
        monthKey: monthKey,
        title: 'Monthly Cardio Committer',
        description: 'Completed 500 minutes (8.3 hours) of cardio - equivalent to climbing the Empire State Building 3 times!',
        icon: FontAwesomeIcons.shoePrints,
        color: CoreColors.coreBronze,
        type: HealthItemType.cardioTime,
        requirement: 500,
        tier: 1,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.cardioTime] ?? 0,
      ),

      // SLEEP MONTHLY TOTALS
      _createMonthlyMedal(
        baseId: 'sleep-total_270h',
        monthKey: monthKey,
        title: 'Monthly Sleep Master',
        description: 'Logged 270 hours of sleep - more than a bear\'s monthly hibernation!',
        icon: FontAwesomeIcons.moon,
        color: CoreColors.coreDiamond,
        type: HealthItemType.sleep,
        requirement: 16200, // minutes
        tier: 4,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep-total_240h',
        monthKey: monthKey,
        title: 'Monthly Dream Weaver',
        description: 'Achieved 240 hours of sleep - that\'s optimal sleep for a full month!',
        icon: FontAwesomeIcons.bed,
        color: CoreColors.coreGold,
        type: HealthItemType.sleep,
        requirement: 14400,
        tier: 3,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep-total_210h',
        monthKey: monthKey,
        title: 'Monthly Rest Champion',
        description: 'Logged 210 hours of sleep - better than 70% of adults!',
        icon: FontAwesomeIcons.cloudMoon,
        color: CoreColors.coreSilver,
        type: HealthItemType.sleep,
        requirement: 12600,
        tier: 2,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep-total_180h',
        monthKey: monthKey,
        title: 'Monthly Sleep Tracker',
        description: 'Achieved 180 hours of sleep - building consistent sleep habits!',
        icon: FontAwesomeIcons.clock,
        color: CoreColors.coreBronze,
        type: HealthItemType.sleep,
        requirement: 10800,
        tier: 1,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.sleep] ?? 0,
      ),

      // PROTEIN MONTHLY TOTALS
      _createMonthlyMedal(
        baseId: 'protein-total_4500',
        monthKey: monthKey,
        title: 'Monthly Protein Legend',
        description: 'Consumed 4,500g of protein - equivalent to 18 whole chickens!',
        icon: FontAwesomeIcons.drumstickBite,
        color: CoreColors.coreDiamond,
        type: HealthItemType.proteinIntake,
        requirement: 4500,
        tier: 4,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein-total_3000',
        monthKey: monthKey,
        title: 'Monthly Protein Master',
        description: 'Reached 3,000g of protein - that\'s 120 protein shakes!',
        icon: FontAwesomeIcons.egg,
        color: CoreColors.coreGold,
        type: HealthItemType.proteinIntake,
        requirement: 3000,
        tier: 3,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein-total_2250',
        monthKey: monthKey,
        title: 'Monthly Protein Pro',
        description: 'Tracked 2,250g of protein - like eating 90 eggs!',
        icon: FontAwesomeIcons.burger,
        color: CoreColors.coreSilver,
        type: HealthItemType.proteinIntake,
        requirement: 2250,
        tier: 2,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein-total_1500',
        monthKey: monthKey,
        title: 'Monthly Protein Tracker',
        description: 'Achieved 1,500g of protein - equivalent to 60 cans of tuna!',
        icon: FontAwesomeIcons.blender,
        color: CoreColors.coreBronze,
        type: HealthItemType.proteinIntake,
        requirement: 1500,
        tier: 1,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.proteinIntake] ?? 0,
      ),

      // NET CALORIES MONTHLY TOTALS
      _createMonthlyMedal(
        baseId: 'netcalories-total_24k',
        monthKey: monthKey,
        title: 'Monthly Fat Loss Champion',
        description: 'Created a 24,000 calorie deficit for the month - that\'s about 7 pounds of fat burned!',
        icon: FontAwesomeIcons.fireFlameSimple,
        color: CoreColors.coreDiamond,
        type: HealthItemType.netCalories,
        requirement: -24000,
        tier: 4,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.netCalories] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'netcalories-total_18k',
        monthKey: monthKey,
        title: 'Monthly Calorie Master',
        description: 'Achieved an 18,000 calorie deficit for the month - equivalent to burning 5 pounds of body fat!',
        icon: FontAwesomeIcons.chartBar,
        color: CoreColors.coreGold,
        type: HealthItemType.netCalories,
        requirement: -18000,
        tier: 3,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.netCalories] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'netcalories-total_12k',
        monthKey: monthKey,
        title: 'Monthly Deficit Achiever',
        description: 'Created a 12,000 calorie deficit this month - like running 24 five-kilometer races!',
        icon: FontAwesomeIcons.gaugeHigh,
        color: CoreColors.coreSilver,
        type: HealthItemType.netCalories,
        requirement: -12000,
        tier: 2,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.netCalories] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'netcalories-total_6k',
        monthKey: monthKey,
        title: 'Monthly Calorie Controller',
        description: 'Reached a 6,000 calorie deficit for the month - a healthy start to sustainable weight management!',
        icon: FontAwesomeIcons.utensils,
        color: CoreColors.coreBronze,
        type: HealthItemType.netCalories,
        requirement: -6000,
        tier: 1,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.netCalories] ?? 0,
      ),
    ];
  }

  static Medal _createMonthlyMedal({
    required String baseId,
    required String monthKey,
    required String title,
    required String description,
    required IconData icon,
    required Color color,
    required HealthItemType type,
    required double requirement,
    required int tier,
    required MedalType medalType,
    required double value,
  }) {
    // Special handling for netCalories, where negative values are better
    bool isEarned = type == HealthItemType.netCalories
        ? (requirement < 0 ? value <= requirement : value >= requirement)
        : value >= requirement;

    return Medal(
      id: '${baseId}_$monthKey',
      title: title,
      description: description,
      icon: icon,
      color: color,
      type: type,
      requirement: requirement,
      tier: tier,
      medalType: medalType,
      isEarned: isEarned,
    );
  }
} 
