import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:healthxp/constants/colors.constants.dart';
import 'package:healthxp/enums/health_item_type.enum.dart';
import 'package:healthxp/models/monthly_medal.model.dart';

enum MedalType {
  allTime,    // Based on total across all months
  monthlyAverage,  // Based on average for a specific month
  monthlyTotal,    // Based on total for a specific month
}

class MedalDefinitions {
  static List<Medal> getAllTimeMedals(Map<HealthItemType, double> allTimeTotals) {
    return [
      // STEPS ALL-TIME
      Medal(
        id: 'steps_2m',
        title: 'World Trekker',
        description: 'Incredible! 2 million steps - equivalent to walking from New York to Miami!',
        icon: FontAwesomeIcons.earthAmericas,
        color: CoreColors.coreDiamond,
        type: HealthItemType.steps,
        requirement: 2000000,
        tier: 4,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.steps] ?? 0) >= 2000000,
      ),
      Medal(
        id: 'steps_1m',
        title: 'Continental Explorer',
        description: 'Reached 1 million steps - you could have walked across the Grand Canyon 12 times!',
        icon: FontAwesomeIcons.mountain,
        color: CoreColors.coreGold,
        type: HealthItemType.steps,
        requirement: 1000000,
        tier: 3,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.steps] ?? 0) >= 1000000,
      ),
      Medal(
        id: 'steps_500k',
        title: 'Urban Explorer',
        description: 'Hit 500,000 steps - equivalent to climbing the CN Tower 250 times!',
        icon: FontAwesomeIcons.personRunning,
        color: CoreColors.coreSilver,
        type: HealthItemType.steps,
        requirement: 500000,
        tier: 2,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.steps] ?? 0) >= 500000,
      ),
      Medal(
        id: 'steps_100k',
        title: 'Path Pioneer',
        description: 'Completed 100,000 steps - you\'ve walked the entire Las Vegas Strip 8 times!',
        icon: FontAwesomeIcons.personWalking,
        color: CoreColors.coreBronze,
        type: HealthItemType.steps,
        requirement: 100000,
        tier: 1,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.steps] ?? 0) >= 100000,
      ),

      // WORKOUT TIME ALL-TIME
      Medal(
        id: 'workout_20k',
        title: 'Legendary Athlete',
        description: 'Completed 20,000 minutes (333 hours) of workouts - equivalent to 14 straight days of training!',
        icon: FontAwesomeIcons.crown,
        color: CoreColors.coreDiamond,
        type: HealthItemType.workoutTime,
        requirement: 20000,
        tier: 4,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.workoutTime] ?? 0) >= 20000,
      ),
      Medal(
        id: 'workout_10k',
        title: 'Elite Trainer',
        description: 'Achieved 10,000 minutes (167 hours) of workouts - that\'s like completing 40 marathons!',
        icon: FontAwesomeIcons.dumbbell,
        color: CoreColors.coreGold,
        type: HealthItemType.workoutTime,
        requirement: 10000,
        tier: 3,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.workoutTime] ?? 0) >= 10000,
      ),
      Medal(
        id: 'workout_5k',
        title: 'Fitness Enthusiast',
        description: 'Reached 5,000 minutes (83 hours) - you\'ve worked out longer than an astronaut\'s basic training!',
        icon: FontAwesomeIcons.heartPulse,
        color: CoreColors.coreSilver,
        type: HealthItemType.workoutTime,
        requirement: 5000,
        tier: 2,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.workoutTime] ?? 0) >= 5000,
      ),
      Medal(
        id: 'workout_1k',
        title: 'Workout Warrior',
        description: 'Completed 1,000 minutes (16.7 hours) of exercise - equivalent to running 6 marathons!',
        icon: FontAwesomeIcons.personRunning,
        color: CoreColors.coreBronze,
        type: HealthItemType.workoutTime,
        requirement: 1000,
        tier: 1,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.workoutTime] ?? 0) >= 1000,
      ),

      // SLEEP ALL-TIME
      Medal(
        id: 'sleep_4k',
        title: 'Sleep Master',
        description: '4,000 hours of tracked sleep - you\'ve slept longer than a space mission to Mars!',
        icon: FontAwesomeIcons.moon,
        color: CoreColors.coreDiamond,
        type: HealthItemType.sleep,
        requirement: 240000, // minutes
        tier: 4,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.sleep] ?? 0) >= 240000,
      ),
      Medal(
        id: 'sleep_3k',
        title: 'Dream Weaver',
        description: '3,000 hours of quality sleep - equivalent to hibernating like a bear!',
        icon: FontAwesomeIcons.bed,
        color: CoreColors.coreGold,
        type: HealthItemType.sleep,
        requirement: 180000,
        tier: 3,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.sleep] ?? 0) >= 180000,
      ),
      Medal(
        id: 'sleep_2k',
        title: 'Rest Champion',
        description: '2,000 hours of tracked sleep - you\'ve outslept a koala\'s monthly nap time!',
        icon: FontAwesomeIcons.cloudMoon,
        color: CoreColors.coreSilver,
        type: HealthItemType.sleep,
        requirement: 120000,
        tier: 2,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.sleep] ?? 0) >= 120000,
      ),
      Medal(
        id: 'sleep_1k',
        title: 'Sleep Tracker',
        description: '1,000 hours of tracked sleep - that\'s more than a sloth sleeps in 2 months!',
        icon: FontAwesomeIcons.clock,
        color: CoreColors.coreBronze,
        type: HealthItemType.sleep,
        requirement: 60000,
        tier: 1,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.sleep] ?? 0) >= 60000,
      ),

      // PROTEIN ALL-TIME
      Medal(
        id: 'protein_100k',
        title: 'Protein Legend',
        description: '100,000g of protein consumed - equivalent to eating 400 whole chickens!',
        icon: FontAwesomeIcons.drumstickBite,
        color: CoreColors.coreDiamond,
        type: HealthItemType.proteinIntake,
        requirement: 100000,
        tier: 4,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.proteinIntake] ?? 0) >= 100000,
      ),
      Medal(
        id: 'protein_50k',
        title: 'Muscle Maven',
        description: '50,000g of protein tracked - that\'s like eating 2,000 eggs!',
        icon: FontAwesomeIcons.egg,
        color: CoreColors.coreGold,
        type: HealthItemType.proteinIntake,
        requirement: 50000,
        tier: 3,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.proteinIntake] ?? 0) >= 50000,
      ),
      Medal(
        id: 'protein_25k',
        title: 'Protein Pro',
        description: '25,000g of protein consumed - equivalent to 100 steaks!',
        icon: FontAwesomeIcons.burger,
        color: CoreColors.coreSilver,
        type: HealthItemType.proteinIntake,
        requirement: 25000,
        tier: 2,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.proteinIntake] ?? 0) >= 25000,
      ),
      Medal(
        id: 'protein_10k',
        title: 'Protein Tracker',
        description: '10,000g of protein logged - that\'s 400 protein shakes!',
        icon: FontAwesomeIcons.blender,
        color: CoreColors.coreBronze,
        type: HealthItemType.proteinIntake,
        requirement: 10000,
        tier: 1,
        medalType: MedalType.allTime,
        isEarned: (allTimeTotals[HealthItemType.proteinIntake] ?? 0) >= 10000,
      ),
    ];
  }

  static List<Medal> getMonthlyAverageMedals(String monthKey, Map<HealthItemType, double> monthlyAverages) {
    return [
      // STEPS MONTHLY AVERAGE
      _createMonthlyMedal(
        baseId: 'steps_15k_avg',
        monthKey: monthKey,
        title: 'Elite Stepper',
        description: 'Averaged 15,000 steps daily - surpassing WHO\'s recommended goal by 50%!',
        icon: FontAwesomeIcons.personRunning,
        color: CoreColors.coreDiamond,
        type: HealthItemType.steps,
        requirement: 15000,
        tier: 4,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.steps] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'steps_10k_avg',
        monthKey: monthKey,
        title: 'Step Master',
        description: 'Averaged 10,000 steps daily - meeting the perfect healthy lifestyle goal!',
        icon: FontAwesomeIcons.personWalking,
        color: CoreColors.coreGold,
        type: HealthItemType.steps,
        requirement: 10000,
        tier: 3,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.steps] ?? 0,
      ),

      // STEPS MONTHLY AVERAGE (continued)
      _createMonthlyMedal(
        baseId: 'steps_7500_avg',
        monthKey: monthKey,
        title: 'Active Achiever',
        description: 'Averaged 7,500 steps daily - you\'re in the top 30% of active people!',
        icon: FontAwesomeIcons.personWalking,
        color: CoreColors.coreSilver,
        type: HealthItemType.steps,
        requirement: 7500,
        tier: 2,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.steps] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'steps_5000_avg',
        monthKey: monthKey,
        title: 'Consistent Stepper',
        description: 'Averaged 5,000 steps daily - building healthy habits one step at a time!',
        icon: FontAwesomeIcons.shoePrints,
        color: CoreColors.coreBronze,
        type: HealthItemType.steps,
        requirement: 5000,
        tier: 1,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.steps] ?? 0,
      ),

      // WORKOUT TIME MONTHLY AVERAGE
      _createMonthlyMedal(
        baseId: 'workout_60_avg',
        monthKey: monthKey,
        title: 'Fitness Fanatic',
        description: 'Averaged 60 minutes of daily exercise - double the CDC recommendation!',
        icon: FontAwesomeIcons.dumbbell,
        color: CoreColors.coreDiamond,
        type: HealthItemType.workoutTime,
        requirement: 60,
        tier: 4,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.workoutTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'workout_45_avg',
        monthKey: monthKey,
        title: 'Workout Warrior',
        description: 'Averaged 45 minutes of daily exercise - crushing the fitness game!',
        icon: FontAwesomeIcons.heartPulse,
        color: CoreColors.coreGold,
        type: HealthItemType.workoutTime,
        requirement: 45,
        tier: 3,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.workoutTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'workout_30_avg',
        monthKey: monthKey,
        title: 'Exercise Enthusiast',
        description: 'Averaged 30 minutes of daily exercise - meeting WHO\'s recommendation!',
        icon: FontAwesomeIcons.personRunning,
        color: CoreColors.coreSilver,
        type: HealthItemType.workoutTime,
        requirement: 30,
        tier: 2,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.workoutTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'workout_15_avg',
        monthKey: monthKey,
        title: 'Active Starter',
        description: 'Averaged 15 minutes of daily exercise - building a healthy routine!',
        icon: FontAwesomeIcons.personWalking,
        color: CoreColors.coreBronze,
        type: HealthItemType.workoutTime,
        requirement: 15,
        tier: 1,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.workoutTime] ?? 0,
      ),

      // SLEEP MONTHLY AVERAGE
      _createMonthlyMedal(
        baseId: 'sleep_9h_avg',
        monthKey: monthKey,
        title: 'Sleep Champion',
        description: 'Averaged 9 hours of sleep daily - optimal rest for peak performance!',
        icon: FontAwesomeIcons.moon,
        color: CoreColors.coreDiamond,
        type: HealthItemType.sleep,
        requirement: 540, // minutes
        tier: 4,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep_8h_avg',
        monthKey: monthKey,
        title: 'Rest Master',
        description: 'Averaged 8 hours of sleep daily - the perfect night\'s rest!',
        icon: FontAwesomeIcons.bed,
        color: CoreColors.coreGold,
        type: HealthItemType.sleep,
        requirement: 480,
        tier: 3,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep_7h_avg',
        monthKey: monthKey,
        title: 'Sleep Tracker',
        description: 'Averaged 7 hours of sleep daily - maintaining healthy sleep habits!',
        icon: FontAwesomeIcons.cloudMoon,
        color: CoreColors.coreSilver,
        type: HealthItemType.sleep,
        requirement: 420,
        tier: 2,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep_6h_avg',
        monthKey: monthKey,
        title: 'Rest Achiever',
        description: 'Averaged 6 hours of sleep daily - working on better sleep habits!',
        icon: FontAwesomeIcons.clock,
        color: CoreColors.coreBronze,
        type: HealthItemType.sleep,
        requirement: 360,
        tier: 1,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.sleep] ?? 0,
      ),

      // PROTEIN MONTHLY AVERAGE
      _createMonthlyMedal(
        baseId: 'protein_150_avg',
        monthKey: monthKey,
        title: 'Protein Elite',
        description: 'Averaged 150g protein daily - optimal for muscle growth!',
        icon: FontAwesomeIcons.drumstickBite,
        color: CoreColors.coreDiamond,
        type: HealthItemType.proteinIntake,
        requirement: 150,
        tier: 4,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein_100_avg',
        monthKey: monthKey,
        title: 'Protein Pro',
        description: 'Averaged 100g protein daily - perfect for active lifestyle!',
        icon: FontAwesomeIcons.egg,
        color: CoreColors.coreGold,
        type: HealthItemType.proteinIntake,
        requirement: 100,
        tier: 3,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein_75_avg',
        monthKey: monthKey,
        title: 'Protein Tracker',
        description: 'Averaged 75g protein daily - meeting basic fitness needs!',
        icon: FontAwesomeIcons.burger,
        color: CoreColors.coreSilver,
        type: HealthItemType.proteinIntake,
        requirement: 75,
        tier: 2,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein_50_avg',
        monthKey: monthKey,
        title: 'Protein Starter',
        description: 'Averaged 50g protein daily - building healthy eating habits!',
        icon: FontAwesomeIcons.blender,
        color: CoreColors.coreBronze,
        type: HealthItemType.proteinIntake,
        requirement: 50,
        tier: 1,
        medalType: MedalType.monthlyAverage,
        value: monthlyAverages[HealthItemType.proteinIntake] ?? 0,
      ),
    ];
  }

  static List<Medal> getMonthlyTotalMedals(String monthKey, Map<HealthItemType, double> monthlyTotals) {
    return [
      // STEPS MONTHLY TOTALS
      _createMonthlyMedal(
        baseId: 'steps_400k_month',
        monthKey: monthKey,
        title: 'Monthly Marathon Master',
        description: 'Crushed 400,000 steps in a month - you\'ve walked the length of Ireland!',
        icon: FontAwesomeIcons.mountain,
        color: CoreColors.coreDiamond,
        type: HealthItemType.steps,
        requirement: 400000,
        tier: 4,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.steps] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'steps_300k_month',
        monthKey: monthKey,
        title: 'Monthly Explorer',
        description: 'Reached 300,000 steps in a month - equivalent to hiking the Grand Canyon rim-to-rim!',
        icon: FontAwesomeIcons.personHiking,
        color: CoreColors.coreGold,
        type: HealthItemType.steps,
        requirement: 300000,
        tier: 3,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.steps] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'steps_200k_month',
        monthKey: monthKey,
        title: 'Monthly Pathfinder',
        description: 'Completed 200,000 steps in a month - you\'ve walked the length of Manhattan 4 times!',
        icon: FontAwesomeIcons.route,
        color: CoreColors.coreSilver,
        type: HealthItemType.steps,
        requirement: 200000,
        tier: 2,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.steps] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'steps_100k_month',
        monthKey: monthKey,
        title: 'Monthly Stepper',
        description: 'Achieved 100,000 steps in a month - that\'s like walking the Golden Gate Bridge 30 times!',
        icon: FontAwesomeIcons.shoePrints,
        color: CoreColors.coreBronze,
        type: HealthItemType.steps,
        requirement: 100000,
        tier: 1,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.steps] ?? 0,
      ),

      // WORKOUT TIME MONTHLY TOTALS
      _createMonthlyMedal(
        baseId: 'workout_1500_month',
        monthKey: monthKey,
        title: 'Monthly Fitness Legend',
        description: 'Logged 1,500 minutes (25 hours) of exercise - that\'s like doing 6 triathlons!',
        icon: FontAwesomeIcons.crown,
        color: CoreColors.coreDiamond,
        type: HealthItemType.workoutTime,
        requirement: 1500,
        tier: 4,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.workoutTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'workout_1000_month',
        monthKey: monthKey,
        title: 'Monthly Fitness Champion',
        description: 'Completed 1,000 minutes (16.7 hours) of exercise - equivalent to running 4 marathons!',
        icon: FontAwesomeIcons.dumbbell,
        color: CoreColors.coreGold,
        type: HealthItemType.workoutTime,
        requirement: 1000,
        tier: 3,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.workoutTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'workout_750_month',
        monthKey: monthKey,
        title: 'Monthly Exercise Pro',
        description: 'Achieved 750 minutes (12.5 hours) of exercise - like climbing Mount Kilimanjaro!',
        icon: FontAwesomeIcons.personRunning,
        color: CoreColors.coreSilver,
        type: HealthItemType.workoutTime,
        requirement: 750,
        tier: 2,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.workoutTime] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'workout_500_month',
        monthKey: monthKey,
        title: 'Monthly Workout Warrior',
        description: 'Completed 500 minutes (8.3 hours) of exercise - equivalent to walking a marathon!',
        icon: FontAwesomeIcons.heartPulse,
        color: CoreColors.coreBronze,
        type: HealthItemType.workoutTime,
        requirement: 500,
        tier: 1,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.workoutTime] ?? 0,
      ),

      // SLEEP MONTHLY TOTALS
      _createMonthlyMedal(
        baseId: 'sleep_270h_month',
        monthKey: monthKey,
        title: 'Monthly Sleep Master',
        description: 'Logged 270 hours of sleep - more than a bear\'s monthly hibernation!',
        icon: FontAwesomeIcons.moon,
        color: CoreColors.coreDiamond,
        type: HealthItemType.sleep,
        requirement: 16200, // minutes
        tier: 4,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep_240h_month',
        monthKey: monthKey,
        title: 'Monthly Dream Weaver',
        description: 'Achieved 240 hours of sleep - that\'s optimal sleep for a full month!',
        icon: FontAwesomeIcons.bed,
        color: CoreColors.coreGold,
        type: HealthItemType.sleep,
        requirement: 14400,
        tier: 3,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep_210h_month',
        monthKey: monthKey,
        title: 'Monthly Rest Champion',
        description: 'Logged 210 hours of sleep - better than 70% of adults!',
        icon: FontAwesomeIcons.cloudMoon,
        color: CoreColors.coreSilver,
        type: HealthItemType.sleep,
        requirement: 12600,
        tier: 2,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.sleep] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'sleep_180h_month',
        monthKey: monthKey,
        title: 'Monthly Sleep Tracker',
        description: 'Achieved 180 hours of sleep - building consistent sleep habits!',
        icon: FontAwesomeIcons.clock,
        color: CoreColors.coreBronze,
        type: HealthItemType.sleep,
        requirement: 10800,
        tier: 1,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.sleep] ?? 0,
      ),

      // PROTEIN MONTHLY TOTALS
      _createMonthlyMedal(
        baseId: 'protein_4500_month',
        monthKey: monthKey,
        title: 'Monthly Protein Legend',
        description: 'Consumed 4,500g of protein - equivalent to 18 whole chickens!',
        icon: FontAwesomeIcons.drumstickBite,
        color: CoreColors.coreDiamond,
        type: HealthItemType.proteinIntake,
        requirement: 4500,
        tier: 4,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein_3000_month',
        monthKey: monthKey,
        title: 'Monthly Protein Master',
        description: 'Reached 3,000g of protein - that\'s 120 protein shakes!',
        icon: FontAwesomeIcons.egg,
        color: CoreColors.coreGold,
        type: HealthItemType.proteinIntake,
        requirement: 3000,
        tier: 3,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein_2250_month',
        monthKey: monthKey,
        title: 'Monthly Protein Pro',
        description: 'Tracked 2,250g of protein - like eating 90 eggs!',
        icon: FontAwesomeIcons.burger,
        color: CoreColors.coreSilver,
        type: HealthItemType.proteinIntake,
        requirement: 2250,
        tier: 2,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.proteinIntake] ?? 0,
      ),
      _createMonthlyMedal(
        baseId: 'protein_1500_month',
        monthKey: monthKey,
        title: 'Monthly Protein Tracker',
        description: 'Achieved 1,500g of protein - equivalent to 60 cans of tuna!',
        icon: FontAwesomeIcons.blender,
        color: CoreColors.coreBronze,
        type: HealthItemType.proteinIntake,
        requirement: 1500,
        tier: 1,
        medalType: MedalType.monthlyTotal,
        value: monthlyTotals[HealthItemType.proteinIntake] ?? 0,
      ),
    ];
  }

  static Medal _createMonthlyMedal({
    required String baseId,
    required String monthKey,
    required String title,
    required String description,
    required IconData icon,
    required Color color,
    required HealthItemType type,
    required double requirement,
    required int tier,
    required MedalType medalType,
    required double value,
  }) {
    return Medal(
      id: '${baseId}_$monthKey',
      title: '$title ($monthKey)',
      description: description,
      icon: icon,
      color: color,
      type: type,
      requirement: requirement,
      tier: tier,
      medalType: medalType,
      isEarned: value >= requirement,
    );
  }
} 
