enum HealthItemType {
  proteinIntake,
  exerciseTime,
  sleep,
  expendedEnergy,
  activeCalories,
  restingCalories,
  dietaryCalories,
  netCalories,
  strengthTrainingMinutes,
  strengthTrainingCaloriesBurned,
  cardioMinutes,
  cardioCaloriesBurned,
  steps,
  weight,
  bodyFatPercentage,
}
